lang: "en"
cache:
  player: "metadata" # file or metadata
  entity: "metadata" # file or metadata
resourcepack: true
data:
  type: "SQLITE"
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: ""
    database: "minecraft"
  cache:
    # With these options, you can manage database cache (from OrmLite)
    # The cache system saves the most recent database queries to improve performance. It's highly recommended for use!
    # With the capacity option, you can manage the size of the cache per DAO. Greater - Better Server Performance - More RAM usage
    # Capacity '0' changes the system to default. It means that there can be stored unlimited amount of objects, but they are removed after garbage collection.
    # Test on your server which option is better for you. Disable only if you have a small amount of RAM!
    enabled: true
    capacity: 0
gui:
  closeItem: BARRIER
  pages:
    leftItem: ARROW
    rightItem: ARROW
debug:
  enable: false
  start: true
  stop: true
  language: true
  cache: true
  command: true
  parser: true
  listener: true
  recipe: true
  gui: true
  data: true
  updater: true
  resourcepack: true
  item: true