lang: 'en'
cache:
  player: metadata # file or metadata
  entity: metadata # file or metadata
debug:
  enable: true
  start: true
  stop: true
  language: true
  cache: true
  command: true
  parser: true
  listener: true
  recipe: true