lang: "en"
cache:
  player: "metadata" # file or metadata
  entity: "metadata" # file or metadata
data:
  type: "SQLITE"
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: ""
    database: "minecraft"
debug:
  enable: true
  start: true
  stop: true
  language: true
  cache: true
  command: true
  parser: true
  listener: true
  recipe: true
  gui: true
  data: true